#pragma once

#include "LightsSystem.h"
#include "ScriptingSystem.h"
#include "InputSystem.h"
#include "HierarchySystem.h"
#include "PhysicsSystem.h"
#include "AnimationSystem.h"
#include "SkinningSystem.h"
#include "CameraControlSystem.h"
#include "AudioSystem.h"
#include "rendering/PresentRenderSystem.h"
#include "rendering/2DRenderSystem.h"
#include "rendering/3DRenderSystem.h"
#include "rendering/3d/BillboardSystem.h"